name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'  # Specify the desired pnpm version

      - name: Debug pnpm installation
        run: |
          echo "pnpm location:"
          which pnpm
          echo "pnpm version:"
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri app
        run: pnpm tauri build
